[platformio]
default_envs = debug

; Non-build settings shared by both environments
[env]
platform               = espressif32
board                  = esp32-c3-devkitm-1
framework              = arduino
lib_deps               =
    https://github.com/ttlappalainen/NMEA2000
    https://github.com/ttlappalainen/NMEA0183
    https://github.com/knifter/NMEA2000_TWAI
    
board_build.partitions = min_spiffs.csv

; Common build flags — referenced by both envs via interpolation
[flags]
common =
    -DCORE_DEBUG_LEVEL=0
    -Os
    -DNMEA2000_DISABLED_DEBUG=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

[env:debug]
monitor_speed = 115200
build_flags   =
    ${flags.common}
    -DDEBUG_BUILD

[env:release]
build_flags   =
    ${flags.common}
